### ISSUE TITLE
想问项目打包放到服务器很多数据请求不到怎么解决

### ISSUE THREAD

**Issue by djwIlo** [xiaofei3062/vue-shop#20]
您好，您的代码为什么打包上传到服务器显示不出来，需要怎么操作

**Comment by xiaofei3062** [comment]
GitHub上面的接口地址是假地址，真实地址联系coderwhy001




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofei3062/vue-shop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午3:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xiaofei3062/vue-shop] 想问项目打包放到服务器很多数据请求不到怎么解决 (#20)





 
您好，您的代码为什么打包上传到服务器显示不出来，需要怎么操作
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by djwIlo** [comment]
能加下你QQ吗

**Comment by djwIlo** [comment]
我在本地可以显示的打包放到云服务器就很多数据请求404

**Comment by xiaofei3062** [comment]
1592826708




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofei3062/vue-shop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午4:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaofei3062/vue-shop] 想问项目打包放到服务器很多数据请求不到怎么解决 (#20)





 
能加下你QQ吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
